name: Deploy to VPS

on:
  workflow_dispatch:

jobs:
  build-and-push:
    steps:
     - name: Hello from CI
       run: echo "first seccessful run"

     - name: checkout the code
       uses: actions/checkout@v4

     - name: see what we get
       run: ls -la